# Generated by Django 5.1.7 on 2025-03-12 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the product name (max 255 characters).', max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Title.', max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, help_text='Content about product', verbose_name='Content')),
                ('image', models.ImageField(blank=True, help_text='Upload the Product Image.', null=True, upload_to='product/%Y/%m/%d/', verbose_name='Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Product price', max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Enter a discount percentage (0 to 100).', max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Disocunt(%)')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Time when the item was created.', verbose_name='Create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='time when the item was update.', verbose_name='Update at')),
                ('time_deleted', models.DateTimeField(blank=True, help_text='Date and time when the object was deleted.', null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producs',
                'ordering': ('-time_create',),
            },
        ),
    ]
