# Generated by Django 5.1.7 on 2025-03-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the brand name.', max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/Y%/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Time when the item was created.', verbose_name='Create at')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='time when the item was update.', verbose_name='Update at')),
                ('time_deleted', models.DateTimeField(blank=True, help_text='Date and time when the object was deleted.', null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('-time_create',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product.', max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, help_text='Upload the category Image.', null=True, upload_to='category/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Time when the item was created.', verbose_name='Create at')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='time when the item was update.', verbose_name='Update at')),
                ('time_deleted', models.DateTimeField(blank=True, help_text='Date and time when the object was deleted.', null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-time_create',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Select a Category for the product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.brand', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select a Category for the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pages.category', verbose_name='Category'),
        ),
    ]
