# Generated by Django 5.1.7 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_brand_category_product_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
