# Generated by Django 5.1.7 on 2025-03-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Select a brand for the product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.brand', verbose_name='Brand'),
        ),
    ]
