# Generated by Django 5.1.7 on 2025-03-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrash',
            fields=[
            ],
            options={
                'verbose_name': 'Trash',
                'verbose_name_plural': 'Product Trash',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-time_create',), 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Select a brand for the product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.brand', verbose_name='Brand'),
        ),
    ]
