# Generated by Django 5.1.7 on 2025-03-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_producttrash_alter_product_options_product_delete_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete_at',
        ),
    ]
